trigger: none
pr: none

resources:
  webhooks:
    - webhook: AcrWebhookTrigger
      connection: AcrWebhookConnection
      filters:
        - path: target.mediaType
          value: "application/vnd.oci.image.manifest.v1+json"

variables:
  - group: caris-quarantine
  - name: sourceAzureSubscription
    value: 'quarantine-helm-publicacr'
  - name: preAzureSubscription
    value: 'quarantine-helm-preacr'
  - name: liveAzureSubscription
    value: 'quarantine-helm-liveacr'
  - name: sourceRegistryServiceConnection
    value: 'publiccrlive-docker' 
  - name: destinationRegistryServiceConnection
    value: 'carisliveacr-docker'
  - name: preRegistryServiceConnection
    value: 'carispreacr-docker'
  - name: destinationRegistry
    value: 'carisliveacr.azurecr.io'
  - name: preRegistry
    value: 'carispreacr.azurecr.io'
  - name: snykServiceConnection
    value: 'SnykAuth'
  - name: snykOrganization
    value: 'caris-cloud'

stages:
- template: templates/helm-scan-template.yml
  parameters:
    sourceAzureSubscription: '$(sourceAzureSubscription)'
    preAzureSubscription: '$(preAzureSubscription)'
    liveAzureSubscription: '$(liveAzureSubscription)'
    sourceRegistryServiceConnection: '$(sourceRegistryServiceConnection)'
    destinationRegistryServiceConnection: '$(destinationRegistryServiceConnection)'
    preRegistryServiceConnection: '$(preRegistryServiceConnection)'
    destinationRegistry: '$(destinationRegistry)'
    preRegistry: '$(preRegistry)'
    snykServiceConnection: '$(snykServiceConnection)'
    snykOrganization: '$(snykOrganization)'
    teamsWebhookEndpoint: '$(teamsWebhookEndpoint)'
    sourceRepository: ${{ parameters.AcrWebhookTrigger.target.repository }}
    sourceTag: ${{ parameters.AcrWebhookTrigger.target.tag }}
    sourceHost: ${{ parameters.AcrWebhookTrigger.request.host }}
