trigger: none
pr: none

resources:
  webhooks:
    - webhook: AcrHelmWebhookTrigger
      connection: AcrWebhookConnection

variables:
  - group: caris-quarantine
  - name: sourceAzureSubscription
    value: 'quarantine-helm-publicacr'
  - name: preAzureSubscription
    value: 'quarantine-helm-preacr'
  - name: liveAzureSubscription
    value: 'quarantine-helm-liveacr'
  - name: sourceRegistryServiceConnection
    value: 'publiccrlive-docker' 
  - name: destinationRegistryServiceConnection
    value: 'carisliveacr-docker'
  - name: preRegistryServiceConnection
    value: 'carispreacr-docker'
  - name: destinationRegistry
    value: 'carisliveacr.azurecr.io'
  - name: preRegistry
    value: 'carispreacr.azurecr.io'
  - name: snykServiceConnection
    value: 'SnykAuth'
  - name: snykOrganization
    value: 'caris-cloud'

stages:
- template: templates/helm-scan-template.yml
  parameters:
    sourceAzureSubscription: '$(sourceAzureSubscription)'
    preAzureSubscription: '$(preAzureSubscription)'
    liveAzureSubscription: '$(liveAzureSubscription)'
    sourceRegistryServiceConnection: '$(sourceRegistryServiceConnection)'
    destinationRegistryServiceConnection: '$(destinationRegistryServiceConnection)'
    preRegistryServiceConnection: '$(preRegistryServiceConnection)'
    destinationRegistry: '$(destinationRegistry)'
    preRegistry: '$(preRegistry)'
    snykServiceConnection: '$(snykServiceConnection)'
    snykOrganization: '$(snykOrganization)'
    teamsWebhookEndpoint: '$(teamsWebhookEndpoint)'
    sourceRepository: ${{ coalesce(parameters.AcrHelmWebhookTrigger.target.repository, parameters.AcrHelmWebhookTrigger.request.target.repository, 'unknown') }}
    sourceTag: ${{ coalesce(parameters.AcrHelmWebhookTrigger.target.tag, parameters.AcrHelmWebhookTrigger.target.version, parameters.AcrHelmWebhookTrigger.request.target.tag, 'unknown') }}
    sourceHost: ${{ coalesce(parameters.AcrHelmWebhookTrigger.request.host, parameters.AcrHelmWebhookTrigger.target.url, 'publiccrlive.azurecr.io') }}
