
trigger: none
pr: none

resources:
  webhooks:
    - webhook: AcrWebhookTrigger
      connection: AcrWebhookConnection
      filters:
        - path: target.mediaType
          value: "application/vnd.oci.image.index.v1+json"

variables:
  # Source registry variables - these are populated from the webhook trigger
  - name: sourceRegistryServiceConnection
    value: 'publiccrlive-docker'
  - name: sourceRepository
    value: ${{ parameters.AcrWebhookTrigger.target.repository }}
  - name: sourceTag
    value: ${{ parameters.AcrWebhookTrigger.target.tag }}
  - name: sourceHost
    value: ${{ parameters.AcrWebhookTrigger.request.host }}
  
  # Destination registry variables
  - name: destinationRegistryServiceConnection
    value: 'destination-docker-registry-connection'
  - name: destinationRegistry
    value: ''
  - name: destinationImageRepository
    value: 'scanned/$(sourceRepository)'
  
  # Snyk variables
  - name: snykServiceConnection
    value: 'SnykAuth'
  - name: snykOrganization
    value: 'caris-cloud'
  
  # Build variables
  - name: scannedImageTag
    value: '$(sourceTag)-snyk-scanned'
  - name: fullDestinationImageName
    value: '$(destinationRegistry)/$(destinationImageRepository):$(scannedImageTag)'

  # Alert Variable
  - name: teamsWebhookEndpoint
    value: ''

stages:
- stage: ScanContainer
  displayName: 'Scan Container'
  jobs:
  - job: ContainerScan
    displayName: 'Scan Pushed Image'
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Snyk scan using UkhoSnykScanTask
    - task: UkhoSnykScanTask@0
      displayName: 'Snyk container scan'
      inputs:
        failOnIssues: true
        organization: '$(snykOrganization)'
        serviceConnectionEndpoint: '$(snykServiceConnection)'
        testType: container
        monitorWhen: never
        severityThreshold: high
        dockerImageName: '$(sourceHost)/$(sourceRepository):$(sourceTag)'

- stage: PushToPrivateRepo
  displayName: 'Push passed image to Private ACR'
  dependsOn: ScanContainer
  condition: succeeded()
  jobs:
  - job: PullTagAndPush
    displayName: 'Pull, Tag and Push the image to the Private ACR'
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Login to destination registry
    - task: Docker@2
      displayName: 'Login to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        command: 'login'

    # Tag the image with snyk-scanned suffix
    - task: Docker@2
      displayName: 'Tag Image as Snyk Scanned'
      inputs:
        command: 'tag'
        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullDestinationImageName)'

    # Push the tagged image to destination registry
    - task: Docker@2
      displayName: 'Push Scanned Image to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        repository: '$(destinationImageRepository)'
        command: 'push'
        tags: '$(scannedImageTag)'

    # Summary step
    - script: |
        echo "✅ Container scanning and push completed successfully!"
        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
        echo "Destination image: $(fullDestinationImageName)"
        echo "Source repository: $(sourceRepository)"
      displayName: 'Pipeline Summary'

- stage: AlertOnFail
  displayName: 'Alert that vulnerable image present'
  dependsOn: ScanContainer
  condition: failed()
  jobs:
  - job: SendTeamsMessage
    displayName: 'Send Alert to Teams Channel'
    steps:
    - task: PowerShell@2
      displayName: 'Send Alert'
      inputs:
        targetType: 'inline'
        script: |
          if ($(teamsWebhookEndpoint) -ne '') {
            $body = @{
              summary = '❌Container scanning and push completed unsuccessfully! Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)'
              text = '❌Container scanning and push completed unsuccessfully!'
            }
            Invoke-WebRequest -Uri $(teamsWebhookEndpoint) -Method Post -Body $body -ContentType 'application/json'
          }

    # Summary step
    - script: |
        echo "❌Container scanning and push completed unsuccessfully!"
        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
        echo "Source repository: $(sourceRepository)"
      displayName: 'Pipeline Summary'









#trigger: none
#pr: none
#
#resources:
#  webhooks:
#    - webhook: AcrWebhookTrigger
#      connection: AcrWebhookConnection
#
#variables:
#  # Source registry variables - these are populated from the webhook trigger
#  - name: sourceRegistryServiceConnection
#    value: 'publiccrlive-docker'
#  - name: sourceRepository
#    value: $(resources.webhook.AcrWebhookTrigger.target.repository)
#  - name: sourceTag
#    value: $(resources.webhook.AcrWebhookTrigger.target.tag)
#  - name: sourceHost
#    value: $(resources.webhook.AcrWebhookTrigger.request.host)
#  
#  # Destination registry variables
#  - name: destinationRegistryServiceConnection
#    value: 'publiccrlive-docker'
#  - name: destinationRegistry
#    value: 'publiccrlive.azurecr.io'
#  - name: destinationImageRepository
#    value: 'scanned/$(sourceRepository)'
#  
#  # Snyk variables
#  - name: snykServiceConnection
#    value: 'SnykAuth'
#  - name: snykOrganization
#    value: 'caris-cloud'
#  
#  # Build variables
#  - name: scannedImageTag
#    value: '$(sourceTag)-snyk-scanned'
#  - name: fullDestinationImageName
#    value: '$(destinationRegistry)/$(destinationImageRepository):$(scannedImageTag)'
#
#  # Alert Variable
#  - name: teamsWebhookEndpoint
#    value: 'https://default9134ca48663d4a05968a31a42f0aed.3e.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/de74f4997f4a422aaca33a0154313553/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=cE4gSKZm6bTSd90iEzhYPndvrXUbFcAOmXafo4UC4OU'
#
#stages:
#- stage: ScanContainer
#  displayName: 'Scan Container'
#  jobs:
#  - job: ContainerScan
#    displayName: 'Scan Pushed Image'
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    # Debug webhook data
#    - task: PowerShell@2
#      displayName: 'Debug Webhook Data'
#      inputs:
#        targetType: 'inline'
#        script: |
#          Write-Host "sourceHost: $(sourceHost)"
#          Write-Host "sourceRepository: $(sourceRepository)"
#          Write-Host "sourceTag: $(sourceTag)"
#          Get-ChildItem env: | Where-Object { $_.Name -like '*webhook*' -or $_.Name -like '*resources*' } | Format-Table -AutoSize
#    
#    # Login to source registry
#    - task: Docker@2
#      displayName: 'Login to Source Registry'
#      inputs:
#        containerRegistry: '$(sourceRegistryServiceConnection)'
#        command: 'login'
#
#    - task: PowerShell@2
#      displayName: 'Pull Published Image'
#      inputs:
#        targetType: 'inline'
#        script: |
#          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)
#
#    # Snyk scan using UkhoSnykScanTask
#    - task: UkhoSnykScanTask@0
#      displayName: 'Snyk container scan'
#      inputs:
#        failOnIssues: true
#        organization: '$(snykOrganization)'
#        serviceConnectionEndpoint: '$(snykServiceConnection)'
#        testType: container
#        monitorWhen: never
#        severityThreshold: high
#        dockerImageName: '$(sourceHost)/$(sourceRepository):$(sourceTag)'
#
#- stage: PushToPrivateRepo
#  displayName: 'Push passed image to Private ACR'
#  dependsOn: ScanContainer
#  condition: succeeded()
#  jobs:
#  - job: PullTagAndPush
#    displayName: 'Pull, Tag and Push the image to the Private ACR'
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    # Login to source registry
#    - task: Docker@2
#      displayName: 'Login to Source Registry'
#      inputs:
#        containerRegistry: '$(sourceRegistryServiceConnection)'
#        command: 'login'
#
#    - task: PowerShell@2
#      displayName: 'Pull Published Image'
#      inputs:
#        targetType: 'inline'
#        script: |
#          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)
#
#    # Login to destination registry
#    - task: Docker@2
#      displayName: 'Login to Destination Registry'
#      inputs:
#        containerRegistry: '$(destinationRegistryServiceConnection)'
#        command: 'login'
#
#    # Tag the image with snyk-scanned suffix
#    - task: Docker@2
#      displayName: 'Tag Image as Snyk Scanned'
#      inputs:
#        command: 'tag'
#        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullDestinationImageName)'
#
#    # Push the tagged image to destination registry
#    - task: Docker@2
#      displayName: 'Push Scanned Image to Destination Registry'
#      inputs:
#        containerRegistry: '$(destinationRegistryServiceConnection)'
#        repository: '$(destinationImageRepository)'
#        command: 'push'
#        tags: '$(scannedImageTag)'
#
#    # Summary step
#    - script: |
#        echo "✅ Container scanning and push completed successfully!"
#        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
#        echo "Destination image: $(fullDestinationImageName)"
#        echo "Source repository: $(sourceRepository)"
#      displayName: 'Pipeline Summary'
#
#- stage: AlertOnFail
#  displayName: 'Alert that vulnerable image present'
#  dependsOn: ScanContainer
#  condition: failed()
#  jobs:
#  - job: SendTeamsMessage
#    displayName: 'Send Alert to Teams Channel'
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - task: PowerShell@2
#      displayName: 'Send Alert'
#      inputs:
#        targetType: 'inline'
#        script: |
#          if ('$(teamsWebhookEndpoint)' -ne '') {
#            $body = @{
#              text = "❌ Container scanning failed!`n`nSource image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
#            } | ConvertTo-Json
#            Invoke-RestMethod -Uri '$(teamsWebhookEndpoint)' -Method Post -Body $body -ContentType 'application/json'
#          }
#
#    # Summary step
#    - script: |
#        echo "❌Container scanning and push completed unsuccessfully!"
#        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
#        echo "Source repository: $(sourceRepository)"
#      displayName: 'Pipeline Summary'


















#trigger: none
#pr: none
#
#parameters:
##  - name: sourceRepository
##    type: string
##    default: ''
##    displayName: 'Source Repository (e.g., test/nginx)'
#  - name: sourceTag
#    type: string
#    default: 'latest' #ukho
#    displayName: 'Source Tag (e.g., alpine)'
#  - name: sourceHost
#    type: string
#    default: 'publiccrlive.azurecr.io'
#    displayName: 'Source Registry Host'
#
#variables:
#  # Source registry variables
#  - name: sourceRegistryServiceConnection
#    value: 'publiccrlive-docker'
#  #- name: sourceRepository
#  #  value: ${{ parameters.sourceRepository }}
#  - name: sourceTag
#    value: ${{ parameters.sourceTag }}
#  - name: sourceHost
#    value: ${{ parameters.sourceHost }}
#  
#  # Destination registry variables
#  - name: destinationRegistryServiceConnection
#    value: 'publiccrlive-docker'
#  - name: destinationRegistry
#    value: 'publiccrlive.azurecr.io'
#  - name: destinationImageRepository
#    value: 'scanned/$(sourceRepository)'
#  
#  # Snyk variables
#  - name: snykServiceConnection
#    value: 'SnykAuth'
#  - name: snykOrganization
#    value: 'caris-cloud'
#  
#  # Build variables
#  - name: scannedImageTag
#    value: '$(sourceTag)-snyk-scanned'
#  - name: fullDestinationImageName
#    value: '$(destinationRegistry)/$(destinationImageRepository):$(scannedImageTag)'
#
#  # Alert Variable
#  - name: teamsWebhookEndpoint
#    value: 'https://default9134ca48663d4a05968a31a42f0aed.3e.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/de74f4997f4a422aaca33a0154313553/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=cE4gSKZm6bTSd90iEzhYPndvrXUbFcAOmXafo4UC4OU'
#
#stages:
#- stage: ScanContainer
#  displayName: 'Scan Container'
#  jobs:
#  - job: ContainerScan
#    displayName: 'Scan Pushed Image'
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    # Login to source registry
#    - task: Docker@2
#      displayName: 'Login to Source Registry'
#      inputs:
#        containerRegistry: '$(sourceRegistryServiceConnection)'
#        command: 'login'
#
#    - task: PowerShell@2
#      displayName: 'Pull Published Image'
#      inputs:
#        targetType: 'inline'
#        script: |
#          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)
#
#    # Snyk scan using UkhoSnykScanTask
#    - task: UkhoSnykScanTask@0
#      displayName: 'Snyk container scan'
#      inputs:
#        failOnIssues: true
#        organization: '$(snykOrganization)'
#        serviceConnectionEndpoint: '$(snykServiceConnection)'
#        testType: container
#        monitorWhen: never
#        severityThreshold: high
#        dockerImageName: '$(sourceHost)/$(sourceRepository):$(sourceTag)'
#
#- stage: PushToPrivateRepo
#  displayName: 'Push passed image to Private ACR'
#  dependsOn: ScanContainer
#  condition: succeeded()
#  jobs:
#  - job: PullTagAndPush
#    displayName: 'Pull, Tag and Push the image to the Private ACR'
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    # Login to source registry
#    - task: Docker@2
#      displayName: 'Login to Source Registry'
#      inputs:
#        containerRegistry: '$(sourceRegistryServiceConnection)'
#        command: 'login'
#
#    - task: PowerShell@2
#      displayName: 'Pull Published Image'
#      inputs:
#        targetType: 'inline'
#        script: |
#          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)
#
#    # Login to destination registry
#    - task: Docker@2
#      displayName: 'Login to Destination Registry'
#      inputs:
#        containerRegistry: '$(destinationRegistryServiceConnection)'
#        command: 'login'
#
#    # Tag the image with snyk-scanned suffix
#    - task: Docker@2
#      displayName: 'Tag Image as Snyk Scanned'
#      inputs:
#        command: 'tag'
#        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullDestinationImageName)'
#
#    # Push the tagged image to destination registry
#    - task: Docker@2
#      displayName: 'Push Scanned Image to Destination Registry'
#      inputs:
#        containerRegistry: '$(destinationRegistryServiceConnection)'
#        repository: '$(destinationImageRepository)'
#        command: 'push'
#        tags: '$(scannedImageTag)'
#
#    # Summary step
#    - script: |
#        echo "✅ Container scanning and push completed successfully!"
#        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
#        echo "Destination image: $(fullDestinationImageName)"
#        echo "Source repository: $(sourceRepository)"
#      displayName: 'Pipeline Summary'
#
#- stage: AlertOnFail
#  displayName: 'Alert that vulnerable image present'
#  dependsOn: ScanContainer
#  condition: failed()
#  jobs:
#  - job: SendTeamsMessage
#    displayName: 'Send Alert to Teams Channel'
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - task: PowerShell@2
#      displayName: 'Send Alert'
#      inputs:
#        targetType: 'inline'
#        script: |
#          if ('$(teamsWebhookEndpoint)' -ne '') {
#            $body = @{
#              text = "❌ Container scanning failed!`n`nSource image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
#            } | ConvertTo-Json
#            Invoke-RestMethod -Uri '$(teamsWebhookEndpoint)' -Method Post -Body $body -ContentType 'application/json'
#          }
#
#    # Summary step
#    - script: |
#        echo "❌Container scanning and push completed unsuccessfully!"
#        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
#        echo "Source repository: $(sourceRepository)"
#      displayName: 'Pipeline Summary'
#