trigger: none
pr: none

parameters:
  - name: sourceRepository
    type: string
    default: ''
    displayName: 'Source Repository (e.g., test/nginx)'
  - name: sourceTag
    type: string
    default: ''
    displayName: 'Source Tag (e.g., latest)'
  - name: sourceHost
    type: string
    default: 'publiccrlive.azurecr.io'
    displayName: 'Source Registry Host'

variables:
  # Source registry variables
  - name: sourceRegistryServiceConnection
    value: 'publiccrlive-docker'
  - name: sourceRepository
    value: ${{ parameters.sourceRepository }}
  - name: sourceTag
    value: ${{ parameters.sourceTag }}
  - name: sourceHost
    value: ${{ parameters.sourceHost }}
  
  # Destination registry variables
  - name: destinationRegistryServiceConnection
    value: 'publiccrlive-docker'
  - name: destinationRegistry
    value: 'publiccrlive.azurecr.io'
  - name: destinationImageRepository
    value: 'scanned/$(sourceRepository)'
  
  # Snyk variables
  - name: snykServiceConnection
    value: 'SnykAuth'
  - name: snykOrganization
    value: 'caris-cloud'
  
  # Build variables
  - name: scannedImageTag
    value: '$(sourceTag)-snyk-scanned'
  - name: fullDestinationImageName
    value: '$(destinationRegistry)/$(destinationImageRepository):$(scannedImageTag)'

  # Alert Variable
  - name: teamsWebhookEndpoint
    value: 'https://default9134ca48663d4a05968a31a42f0aed.3e.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/de74f4997f4a422aaca33a0154313553/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=cE4gSKZm6bTSd90iEzhYPndvrXUbFcAOmXafo4UC4OU'

stages:
- stage: ScanContainer
  displayName: 'Scan Container'
  jobs:
  - job: ContainerScan
    displayName: 'Scan Pushed Image'
    pool:
      name: 'Mare Nectaris'
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Snyk scan using UkhoSnykScanTask
    - task: UkhoSnykScanTask@0
      displayName: 'Snyk container scan'
      inputs:
        failOnIssues: true
        organization: '$(snykOrganization)'
        serviceConnectionEndpoint: '$(snykServiceConnection)'
        testType: container
        monitorWhen: never
        severityThreshold: high
        dockerImageName: '$(sourceHost)/$(sourceRepository):$(sourceTag)'

- stage: PushToPrivateRepo
  displayName: 'Push passed image to Private ACR'
  dependsOn: ScanContainer
  condition: succeeded()
  jobs:
  - job: PullTagAndPush
    displayName: 'Pull, Tag and Push the image to the Private ACR'
    pool:
      name: 'Mare Nectaris'
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Login to destination registry
    - task: Docker@2
      displayName: 'Login to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        command: 'login'

    # Tag the image with snyk-scanned suffix
    - task: Docker@2
      displayName: 'Tag Image as Snyk Scanned'
      inputs:
        command: 'tag'
        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullDestinationImageName)'

    # Push the tagged image to destination registry
    - task: Docker@2
      displayName: 'Push Scanned Image to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        repository: '$(destinationImageRepository)'
        command: 'push'
        tags: '$(scannedImageTag)'

    # Summary step
    - script: |
        echo "✅ Container scanning and push completed successfully!"
        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
        echo "Destination image: $(fullDestinationImageName)"
        echo "Source repository: $(sourceRepository)"
      displayName: 'Pipeline Summary'

- stage: AlertOnFail
  displayName: 'Alert that vulnerable image present'
  dependsOn: ScanContainer
  condition: failed()
  jobs:
  - job: SendTeamsMessage
    displayName: 'Send Alert to Teams Channel'
    pool:
      name: 'Mare Nectaris'
    steps:
    - task: PowerShell@2
      displayName: 'Send Alert'
      inputs:
        targetType: 'inline'
        script: |
          if ('$(teamsWebhookEndpoint)' -ne '') {
            $body = @{
              text = "❌ Container scanning failed!`n`nSource image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
            } | ConvertTo-Json
            Invoke-RestMethod -Uri '$(teamsWebhookEndpoint)' -Method Post -Body $body -ContentType 'application/json'
          }

    # Summary step
    - script: |
        echo "❌Container scanning and push completed unsuccessfully!"
        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
        echo "Source repository: $(sourceRepository)"
      displayName: 'Pipeline Summary'
