trigger: none
pr: none

resources:
  webhooks:
    - webhook: AcrWebhookTriggerDocker
      connection: AcrWebhookConnection1
      filters:
        - path: target.mediaType
          value: "application/vnd.docker.distribution.manifest.list.v2+json"

variables:
  - name: sourceRegistryServiceConnection
    value: 'publiccrlive-docker'
  - name: destinationRegistryServiceConnection
    value: 'carisliveacr-docker'
  - name: preRegistryServiceConnection
    value: 'carispreacr-docker'
  - name: destinationRegistry
    value: 'carisliveacr.azurecr.io'
  - name: preRegistry
    value: 'carispreacr.azurecr.io'
  - name: snykServiceConnection
    value: 'SnykAuth'
  - name: snykOrganization
    value: 'caris-cloud'
  - name: teamsWebhookEndpoint
    value: 'https://d217d034da18e574a33262c48b5477.aa.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/c67bbc4f253c448c8ec846386c3d9c2d/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=1OVhyr6Nz66emPn1n4l7f0mdc2x0NITBZijEfnO4Krw'

stages:
- template: templates/container-scan-template.yml
  parameters:
    sourceRegistryServiceConnection: '$(sourceRegistryServiceConnection)'
    destinationRegistryServiceConnection: '$(destinationRegistryServiceConnection)'
    preRegistryServiceConnection: '$(preRegistryServiceConnection)'
    destinationRegistry: '$(destinationRegistry)'
    preRegistry: '$(preRegistry)'
    snykServiceConnection: '$(snykServiceConnection)'
    snykOrganization: '$(snykOrganization)'
    teamsWebhookEndpoint: '$(teamsWebhookEndpoint)'
    sourceRepository: ${{ parameters.AcrWebhookTriggerDocker.target.repository }}
    sourceTag: ${{ parameters.AcrWebhookTriggerDocker.target.tag }}
    sourceHost: ${{ parameters.AcrWebhookTriggerDocker.request.host }}