trigger: none
pr: none

resources:
  webhooks:
    - webhook: AcrWebhookTrigger
      connection: AcrWebhookConnection
      filters:
        - path: target.mediaType
          value: "application/vnd.oci.image.index.v1+json"

variables:
  # Source registry variables - these are populated from the webhook trigger
  - name: sourceRegistryServiceConnection
    value: 'publiccrlive-docker'
  - name: sourceRepository
    value: ${{ parameters.AcrWebhookTrigger.target.repository }}
  - name: sourceTag
    value: ${{ parameters.AcrWebhookTrigger.target.tag }}
  - name: sourceHost
    value: ${{ parameters.AcrWebhookTrigger.request.host }}
  
  # Destination registry variables
  - name: destinationRegistryServiceConnection
    value: 'carisliveacr-docker'
  - name: destinationRegistry
    value: 'carisliveacr.azurecr.io'
  - name: destinationImageRepository
    value: 'scanned/$(sourceRepository)'
  
  # Snyk variables
  - name: snykServiceConnection
    value: 'SnykAuth'
  - name: snykOrganization
    value: 'caris-cloud'
  
  # Build variables
  - name: scannedImageTag
    value: '$(sourceTag)-snyk-scanned'
  - name: fullDestinationImageName
    value: '$(destinationRegistry)/$(destinationImageRepository):$(scannedImageTag)'

  # Alert Variable
  - name: teamsWebhookEndpoint
    value: 'https://d217d034da18e574a33262c48b5477.aa.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/c67bbc4f253c448c8ec846386c3d9c2d/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=1OVhyr6Nz66emPn1n4l7f0mdc2x0NITBZijEfnO4Krw'

stages:
- stage: ScanContainer
  displayName: 'Scan Container'
  jobs:
  - job: ContainerScan
    displayName: 'Scan Pushed Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Snyk scan using UkhoSnykScanTask
    - task: UkhoSnykScanTask@0
      displayName: 'Snyk container scan'
      inputs:
        failOnIssues: true
        organization: '$(snykOrganization)'
        serviceConnectionEndpoint: '$(snykServiceConnection)'
        testType: container
        monitorWhen: never
        severityThreshold: high # change to low to test teams alert
        dockerImageName: '$(sourceHost)/$(sourceRepository):$(sourceTag)'

    # Publish a simple scanStatus output so later stages can reliably read the scan result
    - task: PowerShell@2
      name: setScanStatusSucceeded
      displayName: 'Set scanStatus succeeded output'
      condition: succeeded()
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[task.setvariable variable=scanStatus;isOutput=true]Succeeded"

    - task: PowerShell@2
      name: setScanStatusFailed
      displayName: 'Set scanStatus failed output'
      condition: failed()
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[task.setvariable variable=scanStatus;isOutput=true]Failed"

- stage: PushToPrivateRepo
  displayName: 'Push passed image to Private ACR'
  dependsOn:
    - ScanContainer
    - NotifyScanResult
  condition: and(succeeded(), eq(dependencies.ScanContainer.result, 'Succeeded'))
  jobs:
  - job: PullTagAndPush
    displayName: 'Pull, Tag and Push the image to the Private ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
  - stage: NotifyScanResult
    displayName: 'Notify Teams (scan-only)'
    dependsOn: ScanContainer
    condition: always()
    jobs:
    - job: SendScanOnlyNotification
      displayName: 'Send Scan-only Teams Notification'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: PowerShell@2
        displayName: 'Send Scan Result to Teams'
        inputs:
          targetType: 'inline'
          script: |
            $webhookUrl = '$(teamsWebhookEndpoint)'
            $pipelineUrl = "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
            $sourceImage = "$(sourceHost)/$(sourceRepository):$(sourceTag)"

            # Read the job output variables set by the scan job
            $scanSucceeded = '$(dependencies.ScanContainer.outputs[''ContainerScan.setScanStatusSucceeded.scanStatus''])'
            $scanFailed = '$(dependencies.ScanContainer.outputs[''ContainerScan.setScanStatusFailed.scanStatus''])'
            Write-Host "scanSucceeded='$scanSucceeded' scanFailed='$scanFailed'"

            if ($scanSucceeded -eq 'Succeeded') {
              $message = "✅ Snyk scan passed for image: $sourceImage`nView pipeline run: $pipelineUrl"
              $title = "Container Scan Passed"
            } else {
              $message = "❌ Snyk scan failed for image: $sourceImage`nView pipeline run: $pipelineUrl"
              $title = "Container Scan Failed"
            }

            $body = [ordered]@{
              title = $title
              message = $message
              pipelineUrl = $pipelineUrl
              sourceHost = "$(sourceHost)"
              sourceRepository = "$(sourceRepository)"
              sourceTag = "$(sourceTag)"
            } | ConvertTo-Json -Depth 5

            Write-Host "Sending scan-only notification to Teams..."
            try {
              $response = Invoke-RestMethod -Uri $webhookUrl -Method Post -Body $body -ContentType 'application/json'
              Write-Host "Response: $response"
            } catch {
              Write-Host "Error sending scan-only notification: $_"
            }
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Login to destination registry
    - task: Docker@2
      displayName: 'Login to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        command: 'login'

    # Tag the image with snyk-scanned suffix
    - task: Docker@2
      displayName: 'Tag Image as Snyk Scanned'
      inputs:
        command: 'tag'
        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullDestinationImageName)'

    # Push the tagged image to destination registry
    - task: Docker@2
      displayName: 'Push Scanned Image to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        repository: '$(destinationImageRepository)'
        command: 'push'
        tags: '$(scannedImageTag)'

    # Send success alert to Teams for passed scans/pushes
    - task: PowerShell@2
      displayName: 'Send Success Alert to Teams'
      inputs:
        targetType: 'inline'
        script: |
          $webhookUrl = '$(teamsWebhookEndpoint)'
          Write-Host "Webhook URL: $webhookUrl"
          if ($webhookUrl -eq '') {
            Write-Host "Webhook URL is empty - skipping success alert"
            exit 0
          }

          $sourceImage = "$(sourceHost)/$(sourceRepository):$(sourceTag)"
          $destImage = "$(fullDestinationImageName)"
          $pipelineUrl = "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"

          $message = "✅ Container scan passed and image pushed.`nSource: $sourceImage`nDestination: $destImage`nView pipeline run: $pipelineUrl"

          $body = [ordered]@{
            title = "Container Scan Passed"
            message = $message
            pipelineUrl = $pipelineUrl
            sourceHost = "$(sourceHost)"
            sourceRepository = "$(sourceRepository)"
            sourceTag = "$(sourceTag)"
            destinationImage = $destImage
          } | ConvertTo-Json -Depth 5

          Write-Host "Sending success request to Teams webhook..."
          Write-Host "Body: $body"
          try {
            $response = Invoke-RestMethod -Uri $webhookUrl -Method Post -Body $body -ContentType 'application/json'
            Write-Host "Response: $response"
            Write-Host "Success alert sent!"
          } catch {
            Write-Host "Error sending success alert: $_"
          }

    # Summary step
    - script: |
        echo "✅ Container scanning and push completed successfully!"
        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
        echo "Destination image: $(fullDestinationImageName)"
        echo "Source repository: $(sourceRepository)"
      displayName: 'Pipeline Summary'