trigger: none
pr: none

resources:
  webhooks:
    - webhook: AcrWebhookTrigger
      connection: AcrWebhookConnection
      filters:
        - path: target.mediaType
          value: "application/vnd.oci.image.index.v1+json"
        #- path: target.mediaType
        #  value: "application/vnd.docker.distribution.manifest.list.v2+json"

variables:
  # Source registry variables - these are populated from the webhook trigger
  - name: sourceRegistryServiceConnection
    value: 'publiccrlive-docker'
  - name: sourceRepository
    value: ${{ parameters.AcrWebhookTrigger.target.repository }}
  - name: sourceTag
    value: ${{ parameters.AcrWebhookTrigger.target.tag }}
  - name: sourceHost
    value: ${{ parameters.AcrWebhookTrigger.request.host }}
  
  # Destination registry variables
  - name: destinationRegistryServiceConnection
    value: 'carisliveacr-docker'
  - name: destinationRegistry
    value: 'carisliveacr.azurecr.io'
  - name: destinationImageRepository
    value: 'scanned/$(sourceRepository)'
  
  # Pre registry variables (mirror live ACR)
  - name: preRegistryServiceConnection
    value: 'carispreacr-docker'
  - name: preRegistry
    value: 'carispreacr.azurecr.io'
  - name: preImageRepository
    value: 'scanned/$(sourceRepository)'
  - name: fullPreImageName
    value: '$(preRegistry)/$(preImageRepository):$(scannedImageTag)'
  
  # Snyk variables
  - name: snykServiceConnection
    value: 'SnykAuth'
  - name: snykOrganization
    value: 'caris-cloud'
  
  # Build variables
  - name: scannedImageTag
    value: '$(sourceTag)-snyk-scanned'
  - name: vulnerableImageTag
    value: '$(sourceTag)-vulnerable'
  - name: fullDestinationImageName
    value: '$(destinationRegistry)/$(destinationImageRepository):$(scannedImageTag)'
  - name: vulnerableImageRepository
    value: 'vulnerable/$(sourceRepository)'
  - name: fullVulnerableImageName
    value: '$(destinationRegistry)/$(vulnerableImageRepository):$(vulnerableImageTag)'
  # Pre vulnerable variables (mirror live vulnerable behavior)
  - name: preVulnerableImageRepository
    value: 'vulnerable/$(sourceRepository)'
  - name: fullPreVulnerableImageName
    value: '$(preRegistry)/$(preVulnerableImageRepository):$(vulnerableImageTag)'

  # Alert Variable
  - name: teamsWebhookEndpoint
    value: 'https://d217d034da18e574a33262c48b5477.aa.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/c67bbc4f253c448c8ec846386c3d9c2d/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=1OVhyr6Nz66emPn1n4l7f0mdc2x0NITBZijEfnO4Krw'

stages:
- stage: ScanContainer
  displayName: 'Scan Container'
  jobs:
  - job: ContainerScan
    displayName: 'Scan Pushed Image'
    pool: Mare Nectaris
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Snyk scan using UkhoSnykScanTask
    - task: UkhoSnykScanTask@0
      displayName: 'Snyk container scan'
      inputs:
        failOnIssues: true
        organization: '$(snykOrganization)'
        serviceConnectionEndpoint: '$(snykServiceConnection)'
        testType: container
        monitorWhen: always
        severityThreshold: high
        dockerImageName: '$(sourceHost)/$(sourceRepository):$(sourceTag)'

- stage: PushToPreACR
  displayName: 'Push scanned image to Pre ACR'
  dependsOn: ScanContainer
  condition: succeeded()
  jobs:
  - job: PushToPre
    displayName: 'Push to Pre ACR'
    pool: Mare Nectaris
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Login to pre registry
    - task: Docker@2
      displayName: 'Login to Pre Registry'
      inputs:
        containerRegistry: '$(preRegistryServiceConnection)'
        command: 'login'

    # Tag the image for pre
    - task: Docker@2
      displayName: 'Tag Image for Pre'
      inputs:
        command: 'tag'
        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullPreImageName)'

    # Push the tagged image to pre registry
    - task: Docker@2
      displayName: 'Push Scanned Image to Pre Registry'
      inputs:
        containerRegistry: '$(preRegistryServiceConnection)'
        repository: '$(preImageRepository)'
        command: 'push'
        tags: '$(scannedImageTag)'

    # Summary step
    - script: |
        echo "✅ Container pushed to Pre ACR successfully!"
        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
        echo "Pre image: $(fullPreImageName)"
        echo "Source repository: $(sourceRepository)"
      displayName: 'Pre Push Summary'

- stage: PushToPrivateRepo
  displayName: 'Push passed image to Private ACR'
  dependsOn: PushToPreACR
  condition: succeeded()
  jobs:
  - job: PullTagAndPush
    displayName: 'Pull, Tag and Push the image to the Private ACR'
    pool: Mare Nectaris
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Login to destination registry
    - task: Docker@2
      displayName: 'Login to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        command: 'login'

    # Tag the image with snyk-scanned suffix
    - task: Docker@2
      displayName: 'Tag Image as Snyk Scanned'
      inputs:
        command: 'tag'
        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullDestinationImageName)'

    # Push the tagged image to destination registry
    - task: Docker@2
      displayName: 'Push Scanned Image to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        repository: '$(destinationImageRepository)'
        command: 'push'
        tags: '$(scannedImageTag)'

    # Summary step
    - script: |
        echo "✅ Container scanning and push completed successfully!"
        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
        echo "Destination image: $(fullDestinationImageName)"
        echo "Source repository: $(sourceRepository)"
      displayName: 'Pipeline Summary'

- stage: AlertOnSuccess
  displayName: 'Alert that scan completed successfully'
  dependsOn: [PushToPreACR, PushToPrivateRepo]
  condition: succeeded()
  jobs:
  - job: SendSuccessTeamsMessage
    displayName: 'Send Success Alert to Teams Channel'
    pool: Mare Nectaris
    steps:
    - task: PowerShell@2
      displayName: 'Send Teams Alert'
      inputs:
        targetType: 'inline'
        script: |
          $body = @{
            title = "Container Scan Completed Successfully"
            message = "Container scanning passed and image has been pushed to live and pre private registries."
            status = "success"
            sourceHost = "$(sourceHost)"
            sourceRepository = "$(sourceRepository)"
            sourceTag = "$(sourceTag)"
            destinationImage = "$(fullDestinationImageName)"
            preImage = "$(fullPreImageName)"
            pipelineUrl = "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          } | ConvertTo-Json
          
          Invoke-RestMethod -Uri "$(teamsWebhookEndpoint)" -Method Post -Body $body -ContentType 'application/json'

- stage: AlertOnFail
  displayName: 'Alert that vulnerable image present'
  dependsOn: ScanContainer
  condition: failed()
  jobs:
  - job: PushPreVulnerableImage
    displayName: 'Push Vulnerable Image to Pre vulnerable namespace'
    pool: Mare Nectaris
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Login to pre registry
    - task: Docker@2
      displayName: 'Login to Pre Registry'
      inputs:
        containerRegistry: '$(preRegistryServiceConnection)'
        command: 'login'

    # Tag the image as vulnerable for pre
    - task: Docker@2
      displayName: 'Tag Image as Vulnerable for Pre'
      inputs:
        command: 'tag'
        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullPreVulnerableImageName)'

    # Push the vulnerable image to pre registry
    - task: Docker@2
      displayName: 'Push Vulnerable Image to Pre Registry'
      inputs:
        containerRegistry: '$(preRegistryServiceConnection)'
        repository: '$(preVulnerableImageRepository)'
        command: 'push'
        tags: '$(vulnerableImageTag)'

  - job: PushVulnerableImage
    displayName: 'Push Vulnerable Image to vulnerable namespace'
    dependsOn: PushPreVulnerableImage
    pool: Mare Nectaris
    steps:
    # Login to source registry
    - task: Docker@2
      displayName: 'Login to Source Registry'
      inputs:
        containerRegistry: '$(sourceRegistryServiceConnection)'
        command: 'login'

    - task: PowerShell@2
      displayName: 'Pull Published Image'
      inputs:
        targetType: 'inline'
        script: |
          docker pull $(sourceHost)/$(sourceRepository):$(sourceTag)

    # Login to destination registry
    - task: Docker@2
      displayName: 'Login to Destination Registry'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        command: 'login'

    # Tag the image as vulnerable
    - task: Docker@2
      displayName: 'Tag Image as Vulnerable'
      inputs:
        command: 'tag'
        arguments: '$(sourceHost)/$(sourceRepository):$(sourceTag) $(fullVulnerableImageName)'

    # Push the vulnerable image
    - task: Docker@2
      displayName: 'Push Vulnerable Image'
      inputs:
        containerRegistry: '$(destinationRegistryServiceConnection)'
        repository: '$(vulnerableImageRepository)'
        command: 'push'
        tags: '$(vulnerableImageTag)'

  - job: SendFailureTeamsMessage
    displayName: 'Send Failure Alert to Teams Channel'
    dependsOn: [PushPreVulnerableImage, PushVulnerableImage]
    condition: always()
    pool: Mare Nectaris
    steps:
    - task: PowerShell@2
      displayName: 'Send Teams Alert'
      inputs:
        targetType: 'inline'
        script: |
          $body = @{
            title = "Container Scan Failed"
            message = "Container scanning failed due to vulnerabilities detected in image: $(sourceHost)/$(sourceRepository):$(sourceTag). Vulnerable images pushed to live and pre registries."
            status = "failure"
            sourceHost = "$(sourceHost)"
            sourceRepository = "$(sourceRepository)"
            sourceTag = "$(sourceTag)"
            vulnerableImage = "$(fullVulnerableImageName)"
            preVulnerableImage = "$(fullPreVulnerableImageName)"
            pipelineUrl = "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          } | ConvertTo-Json
          
          Invoke-RestMethod -Uri "$(teamsWebhookEndpoint)" -Method Post -Body $body -ContentType 'application/json'

    # Summary step
    - script: |
        echo "❌ Container scanning failed!"
        echo "Source image: $(sourceHost)/$(sourceRepository):$(sourceTag)"
        echo "Source repository: $(sourceRepository)"
      displayName: 'Pipeline Summary'