parameters:
  - name: sourceRegistryServiceConnection
    type: string
  - name: destinationRegistryServiceConnection
    type: string
  - name: preRegistryServiceConnection
    type: string
  - name: destinationRegistry
    type: string
  - name: preRegistry
    type: string
  - name: snykServiceConnection
    type: string
  - name: snykOrganization
    type: string
  - name: teamsWebhookEndpoint
    type: string
  - name: sourceRepository
    type: string
  - name: sourceTag
    type: string
  - name: sourceHost
    type: string

stages:
- stage: ScanContainer
  displayName: 'Scan Container'
  condition: succeeded()
  jobs:
  - job: ContainerScan
    displayName: 'Scan Pushed Image'
    pool:
      name: Tiberius
      demands:
      - ENVIRONMENT -equals BUS
    variables:
      sourceImage: '${{ parameters.sourceHost }}/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}'
    steps:
    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Source Registry'
        containerRegistry: '${{ parameters.sourceRegistryServiceConnection }}'

    - template: steps/docker-pull.yml
      parameters:
        displayName: 'Pull Published Image'
        imageName: '$(sourceImage)'

    - task: UkhoSnykScanTask@0
      displayName: 'Snyk container scan'
      inputs:
        failOnIssues: true
        organization: '${{ parameters.snykOrganization }}'
        serviceConnectionEndpoint: '${{ parameters.snykServiceConnection }}'
        testType: container
        monitorWhen: always
        severityThreshold: high
        dockerImageName: '$(sourceImage)'

- stage: PushToPreACR
  displayName: 'Push scanned image to Pre ACR'
  dependsOn: ScanContainer
  condition: succeeded('ScanContainer')
  jobs:
  - job: PushToPre
    displayName: 'Push to Pre ACR'
    pool:
      name: Tiberius
      demands:
      - ENVIRONMENT -equals ENG
    variables:
      sourceImage: '${{ parameters.sourceHost }}/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}'
      scannedImageTag: '${{ parameters.sourceTag }}-snyk-scanned'
      preImageRepository: 'scanned/${{ parameters.sourceRepository }}'
      fullPreImageName: '${{ parameters.preRegistry }}/scanned/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}-snyk-scanned'
    steps:
    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Source Registry'
        containerRegistry: '${{ parameters.sourceRegistryServiceConnection }}'

    - template: steps/docker-pull.yml
      parameters:
        displayName: 'Pull Published Image'
        imageName: '$(sourceImage)'

    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Pre Registry'
        containerRegistry: '${{ parameters.preRegistryServiceConnection }}'

    - template: steps/docker-tag-push.yml
      parameters:
        sourceImage: '$(sourceImage)'
        targetImage: '$(fullPreImageName)'
        targetRegistry: '${{ parameters.preRegistryServiceConnection }}'
        targetRepository: '$(preImageRepository)'
        targetTag: '$(scannedImageTag)'

- stage: PushToPrivateRepo
  displayName: 'Push passed image to Live ACR'
  dependsOn: PushToPreACR
  condition: succeeded('PushToPreACR')
  jobs:
  - job: PullTagAndPush
    displayName: 'Pull, Tag and Push the image to the Private ACR'
    pool:
      name: Tiberius
      demands:
      - ENVIRONMENT -equals BUS
    variables:
      sourceImage: '${{ parameters.sourceHost }}/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}'
      scannedImageTag: '${{ parameters.sourceTag }}-snyk-scanned'
      destinationImageRepository: 'scanned/${{ parameters.sourceRepository }}'
      fullDestinationImageName: '${{ parameters.destinationRegistry }}/scanned/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}-snyk-scanned'
    steps:
    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Source Registry'
        containerRegistry: '${{ parameters.sourceRegistryServiceConnection }}'

    - template: steps/docker-pull.yml
      parameters:
        displayName: 'Pull Published Image'
        imageName: '$(sourceImage)'

    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Destination Registry'
        containerRegistry: '${{ parameters.destinationRegistryServiceConnection }}'

    - template: steps/docker-tag-push.yml
      parameters:
        sourceImage: '$(sourceImage)'
        targetImage: '$(fullDestinationImageName)'
        targetRegistry: '${{ parameters.destinationRegistryServiceConnection }}'
        targetRepository: '$(destinationImageRepository)'
        targetTag: '$(scannedImageTag)'
        displayNamePrefix: 'Snyk Scanned - '

- stage: AlertOnSuccess
  displayName: 'Alert that scan completed successfully'
  dependsOn: [PushToPreACR, PushToPrivateRepo]
  condition: and(succeeded('PushToPreACR'), succeeded('PushToPrivateRepo'))
  jobs:
  - job: SendSuccessTeamsMessage
    displayName: 'Send Success Alert to Teams Channel'
    pool: Mare Nectaris
    variables:
      fullDestinationImageName: '${{ parameters.destinationRegistry }}/scanned/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}-snyk-scanned'
      fullPreImageName: '${{ parameters.preRegistry }}/scanned/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}-snyk-scanned'
    steps:
    - template: steps/send-teams-alert.yml
      parameters:
        webhookEndpoint: '${{ parameters.teamsWebhookEndpoint }}'
        title: 'Container Scan Completed Successfully'
        message: 'Container scanning passed and image has been pushed to live and pre private registries.'
        status: 'success'
        sourceHost: '${{ parameters.sourceHost }}'
        sourceRepository: '${{ parameters.sourceRepository }}'
        sourceTag: '${{ parameters.sourceTag }}'
        additionalFields:
          destinationImage: '$(fullDestinationImageName)'
          preImage: '$(fullPreImageName)'

- stage: AlertOnFail
  displayName: 'Alert that vulnerable image present'
  dependsOn: ScanContainer
  condition: failed('ScanContainer')
  jobs:
  - job: PushPreVulnerableImage
    displayName: 'Push Vulnerable Image to Pre ACR'
    pool:
      name: Tiberius
      demands:
      - ENVIRONMENT -equals ENG
    variables:
      sourceImage: '${{ parameters.sourceHost }}/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}'
      vulnerableImageTag: '${{ parameters.sourceTag }}-vulnerable'
      preVulnerableImageRepository: 'vulnerable/${{ parameters.sourceRepository }}'
      fullPreVulnerableImageName: '${{ parameters.preRegistry }}/vulnerable/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}-vulnerable'
    steps:
    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Source Registry'
        containerRegistry: '${{ parameters.sourceRegistryServiceConnection }}'

    - template: steps/docker-pull.yml
      parameters:
        displayName: 'Pull Published Image'
        imageName: '$(sourceImage)'

    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Pre Registry'
        containerRegistry: '${{ parameters.preRegistryServiceConnection }}'

    - template: steps/docker-tag-push.yml
      parameters:
        sourceImage: '$(sourceImage)'
        targetImage: '$(fullPreVulnerableImageName)'
        targetRegistry: '${{ parameters.preRegistryServiceConnection }}'
        targetRepository: '$(preVulnerableImageRepository)'
        targetTag: '$(vulnerableImageTag)'
        displayNamePrefix: 'Vulnerable - '

  - job: PushVulnerableImage
    displayName: 'Push Vulnerable Image to Live ACR'
    dependsOn: PushPreVulnerableImage
    pool:
      name: Tiberius
      demands:
      - ENVIRONMENT -equals BUS
    variables:
      sourceImage: '${{ parameters.sourceHost }}/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}'
      vulnerableImageTag: '${{ parameters.sourceTag }}-vulnerable'
      vulnerableImageRepository: 'vulnerable/${{ parameters.sourceRepository }}'
      fullVulnerableImageName: '${{ parameters.destinationRegistry }}/vulnerable/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}-vulnerable'
    steps:
    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Source Registry'
        containerRegistry: '${{ parameters.sourceRegistryServiceConnection }}'

    - template: steps/docker-pull.yml
      parameters:
        displayName: 'Pull Published Image'
        imageName: '$(sourceImage)'

    - template: steps/docker-login.yml
      parameters:
        displayName: 'Login to Destination Registry'
        containerRegistry: '${{ parameters.destinationRegistryServiceConnection }}'

    - template: steps/docker-tag-push.yml
      parameters:
        sourceImage: '$(sourceImage)'
        targetImage: '$(fullVulnerableImageName)'
        targetRegistry: '${{ parameters.destinationRegistryServiceConnection }}'
        targetRepository: '$(vulnerableImageRepository)'
        targetTag: '$(vulnerableImageTag)'
        displayNamePrefix: 'Vulnerable - '

  - job: SendFailureTeamsMessage
    displayName: 'Send Failure Alert to Teams Channel'
    dependsOn: [PushPreVulnerableImage, PushVulnerableImage]
    condition: always()
    pool: Mare Nectaris
    variables:
      fullVulnerableImageName: '${{ parameters.destinationRegistry }}/vulnerable/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}-vulnerable'
      fullPreVulnerableImageName: '${{ parameters.preRegistry }}/vulnerable/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}-vulnerable'
    steps:
    - template: steps/send-teams-alert.yml
      parameters:
        webhookEndpoint: '${{ parameters.teamsWebhookEndpoint }}'
        title: 'Container Scan Failed'
        message: 'Container scanning failed due to vulnerabilities detected in image: ${{ parameters.sourceHost }}/${{ parameters.sourceRepository }}:${{ parameters.sourceTag }}. Vulnerable images pushed to live and pre registries.'
        status: 'failure'
        sourceHost: '${{ parameters.sourceHost }}'
        sourceRepository: '${{ parameters.sourceRepository }}'
        sourceTag: '${{ parameters.sourceTag }}'
        additionalFields:
          vulnerableImage: '$(fullVulnerableImageName)'
          preVulnerableImage: '$(fullPreVulnerableImageName)'

